services:
  - type: web
    name: cityvoice-back
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p staticfiles/media/
      cp -r media/* staticfiles/media/ || true
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: cityvoice-db
          property: connectionString

databases:
  - name: cityvoice-db
    databaseName: cityvoice
    user: cityvoice_user
