services:
  - type: web
    name: cityvoice-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: ""
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        value: cityvoice-media
      - key: AWS_S3_REGION_NAME
        value: eu-north-1
      - key: DATABASE_URL
        fromDatabase:
          name: cityvoice-db
          property: connectionString

databases:
  - name: cityvoice-db
    databaseName: cityvoice
    user: cityvoice_user
