# Generated by Django 5.2 on 2025-04-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'В процессе'), ('resolved', 'Решение'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
    ]
