# Generated by Django 5.2 on 2025-04-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='longtitude',
            field=models.FloatField(null=True),
        ),
    ]
