# Generated by Django 5.2 on 2025-05-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_location_report_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.TextField(default='Report'),
            preserve_default=False,
        ),
    ]
