# Generated by Django 5.2 on 2025-05-15 10:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_district_report_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
