# Generated by Django 5.2 on 2025-05-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_district_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
