# Generated by Django 5.2 on 2025-05-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_district_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
