# Generated by Django 5.2 on 2025-05-22 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_category_description_category_unit'),
        ('surveys', '0003_alter_surveyresponse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.category'),
            preserve_default=False,
        ),
    ]
